/* eslint-disable no-tabs */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable max-len */
import styles from './styles.module.scss';

const Terms = (): JSX.Element => {
  return (
    <div className={styles.terms}>
      <h4>Terms of Use</h4>
      <div>
        <p><b>Effective date: August 12, 2021</b></p>

        <p>Welcome to PrizeRing. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the "Services"). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at:</p>

        <p>
          Email: <a href="mailto:support@prizering.io">support@prizering.io</a>
        </p>

        <p>These Terms of Use (the "Terms") are a binding contract between you and PrizeRing, Inc. ("PrizeRing," "we" and "us"). Your use of the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document as well as those in the <a href="/legal/privacy-policy">Privacy Policy</a> and any other relevant policies, including without limitation our <a href="/about/rules-and-scoring/">Rules and Scoring</a>. Your use of or participation in certain Services may also be subject to additional policies, rules and/or conditions ("Additional Terms"), which are incorporated herein by reference, and you understand and agree that by using or participating in any such Services, you agree to also comply with these Additional Terms.</p>

        <p>Please read these Terms carefully. They cover important information about Services provided to you and any charges, taxes, and fees we bill you. These Terms include information about future changes to these Terms, limitations of liability, a class action waiver and resolution of disputes by arbitration instead of in court. PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.</p>

        <p>ARBITRATION NOTICE AND CLASS ACTION WAIVER: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION AGREEMENT SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>

        <p><b>Will these Terms ever change?</b></p>

        <p>We are constantly trying to improve our Services, so these Terms may need to change along with our Services. We reserve the right to change the Terms at any time, but if we do, we will place a notice on our site located at <a href="https://prizering.io">prizering.io</a>, send you an email, and/or notify you by some other means.</p>

        <p>If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.</p>

        <p>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</p>

        <p><b>What about my privacy?</b></p>

        <p>PrizeRing takes the privacy of its users very seriously. For the current PrizeRing <a href="/legal/privacy-policy">Privacy Policy</a>, click the preceding link.</p>

        <p>We do not knowingly collect or solicit personally identifiable information from children under 16 years of age; if you are a child under 16 years of age, please do not attempt to register for or otherwise use the Services or send us any personal information. If we learn we have collected personal information from a child under 16 years of age, we will delete that information as quickly as possible. If you believe that a child under 16 years of age may have provided us personal information, please contact us at <a href="mailto:support@prizering.io">support@prizering.io</a>.</p>

        <p><b>What are the basics of using PrizeRing?</b></p>

        <p>You may be required to sign up for an account, select a password and user name ("PrizeRing User ID"), and provide us with certain information or data, such as your contact information. You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your PrizeRing User ID a name that you do not have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.</p>

        <p>Additionally, you may be able to access certain parts or features of the Services by using your account credentials from other services (each, a "Third Party Account"), such as those offered by Google or Facebook. By using the Services through a Third Party Account, you permit us to access certain information from such account for use by the Services. You are ultimately in control of how much information is accessible to us and may exercise such control by adjusting your privacy settings on your Third Party Account.
          You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and have gotten your parent or guardian to agree to these Terms on your behalf).
        </p>

        <p>You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. You will comply with all laws that apply to you, your use of the Services, and your actions and omissions that relate to the Services If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law.</p>

        <p>You will not share your PrizeRing User ID, account or password with anyone, and you must protect the security of your PrizeRing User ID, account, password and any other access tools or credentials. You’re responsible for any activity associated with your PrizeRing User ID and account.</p>

        <p><b>What about messaging?</b></p>

        <p>As part of the Services, you may receive communications through the Services, including messages that PrizeRing sends you (for example, via email). When signing up for the Services, you will receive a welcome message and instructions on how to stop receiving messages.</p>

        <p><b>Are there restrictions in how I can use the Services?</b></p>

        <p>You represent, warrant, and agree that you will not provide or contribute anything, including any Content or User Submission (as those terms are defined below), to the Services, or otherwise use or interact with the Services, in a manner that:</p>

        <p>(a)	infringes or violates the intellectual property rights or any other rights of anyone else (including PrizeRing);
          (b)	violates any law or regulation, including, without limitation, any applicable export control laws, privacy laws or any other purpose not reasonably intended by PrizeRing;
          (c)	is dangerous, harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
          (d)	jeopardizes the security of your PrizeRing User ID, account or anyone else’s (such as allowing someone else to log in to the Services as you);
          (e)	attempts, in any manner, to obtain the password, account, or other security information from any other user;
          (f)	violates the security of any computer network, or cracks any passwords or security encryption codes;
          (g)	runs Maillist, Listserv, any form of auto-responder or "spam" on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);
          (h)	"crawls," "scrapes," or "spiders" any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);
          (i)	copies or stores any significant portion of the Content;or
          (j)	decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.
        </p>

        <p>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</p>

        <p><b>What are my rights in the Services?</b></p>

        <p>The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions (as defined below) and so forth (all of the foregoing, the "Content") are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s rights.</p>

        <p>Subject to these Terms, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for any purpose other than using the Services is expressly prohibited without prior written permission from us. You understand that PrizeRing owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services. The Services may allow you to copy or download certain Content, but please remember that even where these functionalities exist, all the restrictions in this section still apply.
          What about anything I contribute to the Services – do I have to grant any licenses to PrizeRing or to other users?
        </p>

        <p><b>User Submissions</b></p>

        <p>Anything you post, upload, share, store, or otherwise provide through the Services is your "User Submission". Some User Submissions may be viewable by other users. You are solely responsible for all User Submissions you contribute to the Services. You represent that all User Submissions submitted by you are accurate, complete, up-to-date, and in compliance with all applicable laws, rules and regulations.</p>

        <p>You agree that you will not post, upload, share, store, or otherwise provide through the Services any User Submissions that: (i) infringe any third party's copyrights or other rights (e.g., trademark, privacy rights, etc.); (ii) contain sexually explicit content or pornography; (iii) contain hateful, defamatory, or discriminatory content or incite hatred against any individual or group; (iv) exploit minors; (v) depict unlawful acts or extreme violence; (vi) depict animal cruelty or extreme violence towards animals; (vii) promote fraudulent schemes, multi-level marketing (MLM) schemes, get rich quick schemes, online gambling, cash gifting, work from home businesses, or any other dubious money-making ventures; or (viii) that violate any law.</p>

        <p><b>Dwolla</b></p>
        <p>In order to use the payment functionality of PrizeRing's application, you must open a "Dwolla Platform" account provided by Dwolla, Inc. and you must accept the <a href="https://www.dwolla.com/legal/tos/">Dwolla Terms of Service</a> and <a href="https://www.dwolla.com/legal/privacy/">Privacy Policy</a>. Any funds held in the Dwolla account are held by Dwolla's financial institution partners as set out in the <a href="https://www.dwolla.com/legal/tos/">Dwolla Terms of Service</a>. You authorize PrizeRing to collect and share with Dwolla your personal information including full name, email address and financial information, and you are responsible for the accuracy and completeness of that data. You understand that you will access and manage your Dwolla account through PrizeRing's application, and Dwolla account notifications will be sent by PrizeRing, not Dwolla. PrizeRing will provide customer support for your Dwolla account activity, and can be reached at <a href="mailto:support@prizering.io">support@prizering.io</a></p>

        <p><b>Licenses</b></p>

        <p>In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions (see below for more information). Please note that all of the following licenses are subject to our <a href="/legal/privacy-policy">Privacy Policy</a> to the extent they relate to User Submissions that are also your personally-identifiable information.</p>

        <p>For all User Submissions, you hereby grant PrizeRing a license to translate, modify (for technical purposes, for example, making sure your content is viewable on a mobile device as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below.</p>

        <p>If you store a User Submission in your own personal PrizeRing account, in a manner that is not viewable by any other user except you (a "Personal User Submission"), you grant PrizeRing the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so.</p>

        <p>If you share a User Submission in a manner that only certain specified users can view (for example, a private message to one or more other users) (a "Limited Audience User Submission"), then you grant PrizeRing the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.</p>

        <p>If you share a User Submission in a manner that more than just you or certain specified users can view, or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services (each of the foregoing, a "Public User Submission"), then you grant PrizeRing the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all PrizeRing users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.</p>

        <p>You agree that the licenses you grant are royalty-free, perpetual, sublicensable, irrevocable, and worldwide, provided that when you delete your PrizeRing account, we will stop displaying your User Submissions (other than Public User Submissions, which may remain fully available) to other users (if applicable), but you understand and agree that it may not be possible to completely delete that content from PrizeRing’s records, and that your User Submissions may remain viewable elsewhere to the extent that they were copied or stored by other users.</p>

        <p>Certain features of the Services allow you to share information with others, including through your social networks or other Third Party Accounts. When Content is authorized for sharing, we will clearly identify the Content you are authorized to redistribute and the ways you may redistribute it, usually by providing a "share" button on or near the Content. If you share information from the Services with others through your Third Party Accounts, such as your social networks, you authorize PrizeRing to share that information with the applicable Third Party Account provider. Please review the policies of any Third Party Account providers you share information with or through for additional information about how they may use your information. If you redistribute Content, you must be able to edit or delete any Content you redistribute, and you must edit or delete it promptly upon our request.</p>

        <p>Finally, you understand and agree that PrizeRing, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.</p>

        <p><b>Who is responsible for what I see and do on the Services?</b></p>

        <p>Any information or Content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such Content originated, and you access all such information and Content at your own risk, and we aren’t liable for any errors or omissions in that information or Content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.</p>

        <p>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it.</p>

        <p>The Services may contain links or connections to third-party websites or services that are not owned or controlled by PrizeRing. When you access third-party websites or use third-party services, you accept that there are risks in doing so, and that PrizeRing is not responsible for such risks.</p>

        <p>PrizeRing has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third-party websites or by any third party that you interact with through the Services. In addition, PrizeRing will not and cannot monitor, verify, censor or edit the content of any third-party site or service. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service.
          Your interactions with users found on or through the Services, are solely between you and such users. You agree that PrizeRing shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.
        </p>

        <p>If there is a dispute between participants on this site or Services, or between users and any third party, you agree that PrizeRing is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release PrizeRing, its directors, officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. You shall and hereby do waive California Civil Code Section 1542 or any similar law of any jurisdiction, which says in substance: "A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party."</p>

        <p><b>Will PrizeRing ever change the Services?</b></p>

        <p>We’re always trying to improve our Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We’ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn’t always practical. We reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.</p>

        <p><b>Do the Services cost anything?</b></p>

        <p>Some features of the Services are free, and others are subject to payments (the "Paid Services"). Please note that any payment terms presented to you in the process of using or signing up for a Paid Service are deemed part of these Terms.</p>

        <p>If you are using a free version or feature of the Services, we will notify you before any such Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services. Any and all such charges, fees or costs are your sole responsibility. You should consult with your wireless carrier to determine what rates, charges, fees or costs may apply to your use of the Services.</p>

        <p>a. Billing. We use a third-party payment processor (the "Payment Processor") to process amounts you deposit into a payment account linked to your account on the Services (your "Billing Account") for use of the Paid Services. The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processor in addition to these Terms. Currently, we use Dwolla, Inc. as our Payment Processor. You can access Dwolla’s <a href="https://www.dwolla.com/legal/tos/">Terms of Service</a> and <a href="https://www.dwolla.com/legal/privacy/">Privacy Policy</a>. We are not responsible for any error by, or other acts or omissions of, the Payment Processor. By choosing to use Paid Services, you agree to pay us, through the Payment Processor, all charges at the prices then in effect for any use of such Paid Services in accordance with the applicable payment terms, and you authorize us, through the Payment Processor, to charge your chosen payment provider (your "Payment Method"). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that the Payment Processor makes even if it has already requested or received payment.</p>

        <p>b. Payment Method. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.</p>

        <p>c. Current Information Required. YOU MUST PROVIDE CURRENT, COMPLETE AND ACCURATE INFORMATION FOR YOUR BILLING ACCOUNT. YOU MUST PROMPTLY UPDATE ALL INFORMATION TO KEEP YOUR BILLING ACCOUNT CURRENT, COMPLETE AND ACCURATE (SUCH AS A CHANGE IN BILLING ADDRESS, CREDIT CARD NUMBER, OR CREDIT CARD EXPIRATION DATE), AND YOU MUST PROMPTLY NOTIFY US OR OUR PAYMENT PROCESSOR IF YOUR PAYMENT METHOD IS CANCELED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR USER NAME OR PASSWORD. CHANGES TO SUCH INFORMATION CAN BE MADE AT ACCOUNT SETTINGS. IF YOU FAIL TO PROVIDE ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT WE MAY CONTINUE CHARGING YOU FOR ANY USE OF PAID SERVICES UNDER YOUR BILLING ACCOUNT UNLESS YOU HAVE TERMINATED YOUR PAID SERVICES AS SET FORTH ABOVE.</p>

        <p>d. Change in Amount Authorized. If the amount to be charged to your Billing Account varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), you have the right to receive, and we shall provide, notice of the amount to be charged and the date of the charge before the scheduled date of the transaction. Any agreement you have with your payment provider will govern your use of your Payment Method. You agree that we may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.</p>

        <p>e. Free Trials and Other Promotions. Any free trial or other promotion that provides access to a Paid Service must be used within the specified time of the trial. You must stop using a Paid Service before the end of the trial period in order to avoid being charged for that Paid Service. If you cancel prior to the end of the trial period and are inadvertently charged for a Paid Service, please contact us at <a href="mailto:support@prizering.io">support@prizering.io</a>.</p>

        <p><b>What if I want to stop using the Services?</b></p>

        <p>You’re free to do that at any time by contacting us at <a href="mailto:support@prizering.io">support@prizering.io</a>; please refer to our <a href="/legal/privacy-policy">Privacy Policy</a>, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.</p>

        <p>PrizeRing is also free to terminate (or suspend access to) your use of the Services or your account for any reason in our discretion, including your breach of these Terms. PrizeRing has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</p>

        <p>Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.
          If you have deleted your account by mistake, contact us immediately at <a href="mailto:support@prizering.io">support@prizering.io</a>  – we will try to help, but unfortunately, we can’t promise that we can recover or restore anything.
        </p>

        <p>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us.</p>

        <p><b>What about Mobile Applications?</b></p>

        <p>You acknowledge and agree that the availability of our mobile application is dependent on the third party stores from which you download the application, e.g., the App Store from Apple ("App Store"). The App Store may have its own terms and conditions to which you must agree before downloading mobile applications from such store, including the specific terms relating to Apple App Store set forth below. You agree to comply with, and your license to use our application is conditioned upon your compliance with, such App Store terms and conditions. To the extent such other terms and conditions from such App Store are less restrictive than, or otherwise conflict with, the terms and conditions of these Terms of Use, the more restrictive or conflicting terms and conditions in these Terms of Use apply.

        </p><p><b>I use the PrizeRing App available via the Apple App Store – should I know anything about that?</b></p>

        <p>These Terms apply to your use of all the Services, including our iOS application (the "Application") available via the Apple, Inc. ("Apple") App Store, but the following additional terms also apply to the Application:</p>

        <p>(a)	Both you and PrizeRing acknowledge that the Terms are concluded between you and PrizeRing only, and not with Apple, and that Apple is not responsible for the Application or the Content;
          (b)	The Application is licensed to you on a limited, non-exclusive, non-transferrable, non-sublicensable basis, solely to be used in connection with the Services for your private, personal, non-commercial use, subject to all the terms and conditions of these Terms as they are applicable to the Services;
          (c)	You will only use the Application in connection with an Apple device that you own or control;
          (d)	You acknowledge and agree that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Application;
          (e)	 In the event of any failure of the Application to conform to any applicable warranty, including those implied by law, you may notify Apple of such failure; upon notification, Apple’s sole warranty obligation to you will be to refund to you the purchase price, if any, of the Application;
          (f)	You acknowledge and agree that PrizeRing, and not Apple, is responsible for addressing any claims you or any third party may have in relation to the Application;
          (g)	You acknowledge and agree that, in the event of any third-party claim that the Application or your possession and use of the Application infringes that third party’s intellectual property rights, PrizeRing, and not Apple, will be responsible for the investigation, defense, settlement and discharge of any such infringement claim;
          (h)	 You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country, and that you are not listed on any U.S. Government list of prohibited or restricted parties;
          (i)	Both you and PrizeRing acknowledge and agree that, in your use of the Application, you will comply with any applicable third-party terms of agreement which may affect or be affected by such use; and
          (j)	Both you and PrizeRing acknowledge and agree that Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.
        </p>

        <p><b>Can I refer other users?</b></p>

        <p>From time to time PrizeRing may offer rewards or incentives for referring others to the Services. The referring user ("Referrer") may refer individuals or entities who are neither current customers of PrizeRing nor registered users of the Services ("Referee"). A registered user is a person or entity that already has an existing account with PrizeRing. There is no limit to the number of referrals that Referrer can make, nor the cumulative rewards or incentives that the Referrer may receive through such special offer, unless otherwise indicated. Referrer will receive the stated reward or incentive for each Referee sent by the Referrer that completes the required action described in that specific offer (such as signing up for an account or making a purchase). All Referees must be first-time recipients of the offer, and multiple referrals to the same individual or entity will be disregarded. PrizeRing reserves the right to modify or terminate any special offers at any time and to revoke from Referrer and Referee the special offer at PrizeRing’s discretion for any reason or for no reason whatsoever. If PrizeRing determines that Referrer or Referee is attempting to obtain unfair advantage or otherwise violate the terms or spirit of such special offer, PrizeRing reserves the right to (a) revoke any rewards or incentives issued to either Referrer or Referee and/or (b) charge the Referrer or Referee for any rewards or incentives (1) used by Referrer or Referee prior to such revocation or (2) issued by PrizeRing to any ineligible Referrer or Referee. All special offers are subject to any other terms, conditions and restrictions set forth on the Services or presented in connection with the special offer.</p>

        <p><b>What else do I need to know?</b></p>

        <p>Warranty Disclaimer. Except as explicitly set forth in the previous paragraph, PrizeRing and its licensors, suppliers, partners, parent, subsidiaries or affiliated entities, and each of their respective officers, directors, members, employees, consultants, contract employees, representatives and agents, and each of their respective successors and assigns (PrizeRing and all such parties together, the "PrizeRing Parties") make no representations or warranties concerning the Services, including without limitation regarding any Content contained in or accessed through the Services, and the PrizeRing Parties will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services or any claims, actions, suits procedures, costs, expenses, damages or liabilities arising out of use of, or in any way related to your participation in, the Services. The PrizeRing Parties make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through or in connection with the Services. THE SERVICES AND CONTENT ARE PROVIDED BY PrizeRing (AND ITS LICENSORS AND SUPPLIERS) ON AN "AS-IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>

        <p>Limitation of Liability. TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL ANY OF THE PrizeRing PARTIES BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, (B) ANY SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, (C) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) ]ONE-HUNDRED ($100) DOLLARS OR (II) THE AMOUNTS PAID AND/OR PAYABLE BY YOU TO PrizeRing IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM OR (D) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL OR CERTAIN OTHER DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>

        <p>Indemnity. You agree to indemnify and hold the PrizeRing Parties harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action ("Claim"), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).
          Assignment. You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without PrizeRing’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.
          Choice of Law. These Terms are governed by and will be construed under the Federal Arbitration Act, applicable federal law, and the laws of the State of New Hampshire, without regard to the conflicts of laws provisions thereof.
        </p>

        <p>Arbitration Agreement. Please read the following ARBITRATION AGREEMENT carefully because it requires you to arbitrate certain disputes and claims with PrizeRing and limits the manner in which you can seek relief from PrizeRing. Both you and PrizeRing acknowledge and agree that for the purposes of any dispute arising out of or relating to the subject matter of these Terms, PrizeRing’s officers, directors, employees and independent contractors ("Personnel") are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Personnel will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.</p>

        <p>(a) Arbitration Rules; Applicability of Arbitration Agreement. The parties shall use their best efforts to settle any dispute, claim, question, or disagreement arising out of or relating to the subject matter of these Terms directly through good-faith negotiations, which shall be a precondition to either party initiating arbitration. If such negotiations do not resolve the dispute, it shall be finally settled by binding arbitration. The arbitration will proceed in the English language, in accordance with the JAMS Streamlined Arbitration Rules and Procedures (the "Rules") then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes. The arbitrator shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction.</p>

        <p>(b) Costs of Arbitration. The Rules will govern payment of all arbitration fees. PrizeRing will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim is frivolous.</p>

        <p>(c) Small Claims Court; Infringement. Either you or PrizeRing may assert claims, if they qualify, in small claims court in any United States county where you live or work. Furthermore, notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction, to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents or other intellectual property rights.</p>

        <p>(d) Waiver of Jury Trial. YOU AND PrizeRing WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR JURY. You and PrizeRing are instead choosing to have claims and disputes resolved by arbitration. Arbitration procedures are typically more limited, more efficient, and less costly than rules applicable in court and are subject to very limited review by a court. In any litigation between you and PrizeRing over whether to vacate or enforce an arbitration award, YOU AND PrizeRing WAIVE ALL RIGHTS TO A JURY TRIAL, and elect instead to have the dispute be resolved by a judge.</p>

        <p>(e) Waiver of Class or Consolidated Actions. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor PrizeRing is entitled to arbitration; instead all claims and disputes will be resolved in a court as set forth in (g) below.</p>

        <p>(f) Opt-out. You have the right to opt out of the provisions of this Section by sending written notice of your decision to opt out to the following address: [insert address] postmarked within thirty (30) days of first accepting these Terms. You must include (i) your name and residence address, (ii) the email address and/or telephone number associated with your account, and (iii) a clear statement that you want to opt out of these Terms’ arbitration agreement.</p>

        <p>(g) Exclusive Venue. If you send the opt-out notice in (f), and/or in any circumstances where the foregoing arbitration agreement permits either you or PrizeRing to litigate any dispute arising out of or relating to the subject matter of these Terms in court, then the foregoing arbitration agreement will not apply to either party, and both you and PrizeRing agree that any judicial proceeding (other than small claims actions) will be brought in the state or federal courts located in the federal district in which that county falls.</p>

        <p>(h) Severability. If the prohibition against class actions and other claims brought on behalf of third parties contained above is found to be unenforceable, then all of the preceding language in this Arbitration Agreement section will be null and void. This arbitration agreement will survive the termination of your relationship with PrizeRing.
          Miscellaneous. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the PrizeRing may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms are found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and PrizeRing agree that these Terms are the complete and exclusive statement of the mutual understanding between you and PrizeRing, and that these Terms supersede and cancel all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of PrizeRing, and you do not have any authority of any kind to bind PrizeRing in any respect whatsoever.
          Except as expressly set forth in the sections above regarding the Apple Application and the arbitration agreement, you and PrizeRing agree there are no third-party beneficiaries intended under these Terms.
        </p>
      </div>
    </div>
  );
};

export default Terms;
